my_string = input("Введите ваше Ф.И.О: ")
print ("Количество букв в ваших Ф.И.О: ", len (my_string))
print (my_string .upper())
print (my_string .lower())
print (my_string .replace (" ", ""))
print (my_string [0:1])
print (my_string [-1])